package editor;

import java.io.File;
import handlers.*;
import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.geometry.Insets;
import javafx.geometry.Orientation;
import javafx.geometry.Pos;
import javafx.scene.Cursor;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.CheckBox;
import javafx.scene.control.ColorPicker;
import javafx.scene.control.Menu;
import javafx.scene.control.MenuBar;
import javafx.scene.control.MenuItem;
import javafx.scene.control.RadioButton;
import javafx.scene.control.Separator;
import javafx.scene.control.ToggleGroup;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.layout.Region;
import javafx.stage.FileChooser;
import javafx.stage.Stage;

/**
 * ShapeEditor is a JavaFX-based interactive drawing application
 * that allows users to create, edit, and manage geometric shapes
 * such as lines, rectangles, and ovals on a canvas.
 *
 * The application supports multiple interaction modes including
 * drawing, moving, copying, deleting, and grouping shapes, all
 * managed through dedicated event handlers.
 *
 * It also provides features such as undo/redo functionality,
 * color selection, filled vs. outlined shapes, and file
 * persistence (text and binary formats).
 *
 * The UI is structured using a BorderPane layout with a central
 * drawing canvas, a top toolbar for tools and settings, and a
 * bottom menu bar for file operations.
 *
 * Overall, ShapeEditor demonstrates event-driven programming,
 * modular handler design, and basic graphics application architecture
 * using JavaFX.
 * 
 * @author Soikat
 */
public class ShapeEditor extends Application {
    
	// ----- FIELDS -----
	/** Width of the main application window in pixels. */
	private static final int APP_WIDTH = 1200;
	/** Height of the main application window in pixels. */
	private static final int APP_HEIGHT = 780;
	/** Reserved vertical space for the toolbar. */
	private static final int TOOLBAR_RESERVE = 60;
	/** Reserved vertical space for the menubar. */
	private static final int MENUBAR_RESERVE = 28;
	/** Width of the drawing canvas (matches application width). */
	private static final int CANVAS_WIDTH = APP_WIDTH;
	/** Height of the drawing canvas after accounting for UI elements. */
	private static final int CANVAS_HEIGHT = APP_HEIGHT - TOOLBAR_RESERVE - MENUBAR_RESERVE;

	/** Root layout container organizing all UI components. */
    private BorderPane  mainPane;
	/** Custom canvas used for rendering and interacting with shapes. */
	private ShapeCanvas canvas;
	/** Top toolbar containing drawing tools and controls. */
	private HBox        controlPanel;
	/** Buttons to clear all shapes from the canvas, to undo the last action, to redo the previously undone action. */
	private Button      bnClear, bnUndo, bnRedo;
	/** Checkbox to toggle filled vs. outlined shapes. */
	private CheckBox    cbFilled;
	/** Radio buttons to select different actions */
	private RadioButton rbLine, rbOval, rbRect, rbDelete, rbMove, rbCopy, rbGroup;
	/** Handler for line drawing interactions. */
	private LineHandler lineHandler;
	/** Handler for rectangle drawing interactions. */
	private RectHandler rectHandler;
	/** Handler for oval drawing interactions. */
	private OvalHandler ovalHandler;
	/** Handler for deleting shapes. */
	private DeleteHandler deleteHandler;
	/** Handler for moving shapes. */
	private MoveHandler moveHandler;
	/** Handler for copying shapes. */
	private CopyHandler copyHandler;
	/** Handler for grouping shapes. */
	private GroupHandler groupHandler;
	/** Color picker for selecting the current drawing color. */
	private ColorPicker colorPicker;

	/** Menu bar containing file operations. */
	private MenuBar     menuBar;
	/** File menu within the menu bar. */
	private Menu        menuFile;
	/** Menu items for loading, saving shapes from/to a text/binary files. */
	private MenuItem    miLoad, miSave, miLoadB, miSaveB;
	/** File chooser dialog for selecting files to load/save. */
	private FileChooser fileChooser;

	/*
	 * UI Styling Constants – serves as visual aid only
	 *
	 * Defines JavaFX CSS styles for toolbar, menu bar,
	 * buttons, labels, and color picker components.
	 * These ensure a consistent and modern UI appearance.
	 * 
	 * Note: generated by GenAI
	 */
	private static final String TOOLBAR_STYLE =
		"-fx-background-color: #f5f5f7; "
		+ "-fx-border-color: transparent transparent #e5e5ea transparent; "
		+ "-fx-border-width: 0 0 1 0; ";
	private static final String MENU_BAR_STYLE =
		"-fx-background-color: #f5f5f7; "
		+ "-fx-border-color: #e5e5ea transparent transparent transparent; "
		+ "-fx-border-width: 1 0 0 0; "
		+ "-fx-padding: 2 18 2 18; "
		+ "-fx-font-size: 11px; ";
	private static final String TOOL_LABEL_STYLE =
		"-fx-font-size: 11px; -fx-text-fill: #3a3a3c; ";
	private static final String TOOL_BUTTON_STYLE =
		"-fx-background-color: #ffffff; "
		+ "-fx-background-radius: 5; "
		+ "-fx-border-color: #d2d2d7; "
		+ "-fx-border-radius: 5; "
		+ "-fx-border-width: 1; "
		+ "-fx-padding: 5 14 5 14; "
		+ "-fx-font-size: 11px; -fx-text-fill: #1d1d1f; ";
	private static final String TOOL_BUTTON_STYLE_HOVER =
		"-fx-background-color: #ebebed; "
		+ "-fx-background-radius: 5; "
		+ "-fx-border-color: #bcbcc0; "
		+ "-fx-border-radius: 5; "
		+ "-fx-border-width: 1; "
		+ "-fx-padding: 5 14 5 14; "
		+ "-fx-font-size: 11px; -fx-text-fill: #1d1d1f; ";
	private static final String COLOR_PICKER_STYLE =
		"-fx-background-radius: 5; "
		+ "-fx-border-radius: 5; "
		+ "-fx-border-color: #d2d2d7; "
		+ "-fx-border-width: 1; ";

	/**
	 * Entry point for the JavaFX application.
	 * Initializes the main layout, canvas, controls, and menu,
	 * and displays the primary stage.
	 *
	 * @param mainStage the primary stage for this application
	 */
	@Override
    public void start (Stage mainStage)
	{
		mainPane = new BorderPane ();

		setupCanvas ();
		setupControls ();
		setupMenu();

		Scene scene = new Scene (mainPane, APP_WIDTH, APP_HEIGHT);
		mainStage.setScene(scene);
		mainStage.setTitle("Shape Editor Application");
		mainStage.show();
	}

	/**
	 * Initializes and configures the top control panel (toolbar).
	 *
	 * Sets up drawing tools, action buttons (undo/redo/clear),
	 * color selection, and interaction handlers for each mode.
	 */
    public void setupControls ()
    {
		// Set up initial control panel & add basic styles
		controlPanel = new HBox ();
		controlPanel.setSpacing (10);
		controlPanel.setPadding (new Insets (10, 18, 10, 18));
		controlPanel.setAlignment (Pos.CENTER_LEFT);
		controlPanel.setStyle (TOOLBAR_STYLE);
		
		// Instantiate handlers
		lineHandler   = new LineHandler (canvas);
		rectHandler   = new RectHandler (canvas);
        ovalHandler   = new OvalHandler (canvas);
		deleteHandler = new DeleteHandler (canvas);
		moveHandler   = new MoveHandler (canvas);
		copyHandler   = new CopyHandler (canvas);
		groupHandler  = new GroupHandler (canvas);

		// Add radio buttons & set corresponding handlers
		rbLine   = new RadioButton ("Line");
		rbOval   = new RadioButton ("Oval");
		rbRect   = new RadioButton ("Rectangle");
		rbDelete = new RadioButton ("Delete");
		rbMove   = new RadioButton ("Move");
		rbCopy   = new RadioButton ("Copy");
		rbGroup  = new RadioButton ("Group");

		rbLine.setSelected(true);
		canvas.replaceMouseHandler (lineHandler);

		ToggleGroup group = new ToggleGroup ();
		rbLine.setToggleGroup(group);
		rbOval.setToggleGroup(group);
		rbRect.setToggleGroup(group);
		rbDelete.setToggleGroup(group);
		rbMove.setToggleGroup (group);
		rbCopy.setToggleGroup(group);
		rbGroup.setToggleGroup(group);

		rbLine.setOnAction(e -> {
			canvas.replaceMouseHandler (lineHandler);
		});
		rbOval.setOnAction(e -> {
			canvas.replaceMouseHandler (ovalHandler);
		});
		rbRect.setOnAction(e -> {
			canvas.replaceMouseHandler (rectHandler);
		});
		rbDelete.setOnAction(e -> {
			canvas.replaceMouseHandler (deleteHandler);
		});
		rbMove.setOnAction(e -> {
			canvas.replaceMouseHandler(moveHandler);
		});
		rbCopy.setOnAction(e -> {
			canvas.replaceMouseHandler(copyHandler);
		});
		rbGroup.setOnAction(e -> {
			canvas.replaceMouseHandler(groupHandler);
		});

		// Add checkBox
		cbFilled = new CheckBox ("Filled");
		cbFilled.setOnAction(e -> {
			canvas.setCurrFilled(cbFilled.isSelected());
		});

		// Add colorPicker
		colorPicker = new ColorPicker (canvas.getCurrColor());
		colorPicker.setOnAction(new EventHandler<ActionEvent> () {
			@Override
			public void handle (ActionEvent e)
			{
				canvas.setCurrColor(colorPicker.getValue());
			}
		});

		// Add undo, redo & clear button
		bnUndo  = new Button ("Undo");
		bnRedo  = new Button ("Redo");
		bnClear = new Button ("Clear");
		bnUndo.setOnAction(e -> {
			canvas.undo();
		});
		bnRedo.setOnAction(e -> {
			canvas.redo();
		});
		bnClear.setOnAction(e -> {
			canvas.clear();
		});

		// Add styles to node – generated by GenAI
		rbLine.setStyle (TOOL_LABEL_STYLE);
		rbRect.setStyle (TOOL_LABEL_STYLE);
		rbOval.setStyle (TOOL_LABEL_STYLE);
		rbDelete.setStyle (TOOL_LABEL_STYLE);
		rbMove.setStyle (TOOL_LABEL_STYLE);
		rbCopy.setStyle (TOOL_LABEL_STYLE);
		rbGroup.setStyle (TOOL_LABEL_STYLE);
		cbFilled.setStyle (TOOL_LABEL_STYLE);
		colorPicker.setStyle (COLOR_PICKER_STYLE);
		bnUndo.setStyle (TOOL_BUTTON_STYLE);
		bnRedo.setStyle (TOOL_BUTTON_STYLE);
		bnClear.setStyle (TOOL_BUTTON_STYLE);
		wireToolButtonHover (bnUndo);
		wireToolButtonHover (bnRedo);
		wireToolButtonHover (bnClear);
		Region spring = new Region ();
		HBox.setHgrow (spring, Priority.ALWAYS);

		// Add all nodes: groups + vertical rules + spring so actions sit on the right.
		controlPanel.getChildren ().addAll (
			rbLine, rbRect, rbOval,
			toolbarRule (),
			cbFilled, colorPicker,
			toolbarRule (),
			rbDelete, rbMove, rbCopy, rbGroup,
			spring,
			bnUndo, bnRedo, bnClear
		);
        
		mainPane.setTop(controlPanel);
    }

	/**
	 * Initializes the drawing canvas and places it in the center of the layout.
	 */
    public void setupCanvas ()
	{
		canvas = new ShapeCanvas (CANVAS_WIDTH, CANVAS_HEIGHT);
		mainPane.setCenter(canvas);
	} 

	/**
	 * Initializes the menu bar and configures file operations.
	 *
	 * Supports loading and saving drawings in both text and binary formats.
	 */
	public void setupMenu ()
	{
		menuBar = new MenuBar ();
		menuFile = new Menu ("File");
		menuBar.getMenus().addAll(menuFile);

		miLoad  = new MenuItem ("Load");
		miSave  = new MenuItem ("Save");
		miLoadB = new MenuItem ("Load Binary Format");
		miSaveB = new MenuItem ("Save Binary Format");
		menuFile.getItems().addAll(miLoad, miSave, miLoadB, miSaveB);
		fileChooser = new FileChooser ();

		// sets styles - generated by GenAI
		menuBar.setStyle (MENU_BAR_STYLE);
		menuFile.setStyle (TOOL_LABEL_STYLE);

		miSave.setOnAction(new EventHandler<ActionEvent> () {
			@Override
			public void handle (ActionEvent e)
			{
				fileChooser.setTitle("Save drawing");
				File newFile = fileChooser.showSaveDialog(null);

				if (newFile != null)
					canvas.toTextFile (newFile);
			}
		});

		miLoad.setOnAction(e -> {
			fileChooser.setTitle("Load drawing");
			File newFile = fileChooser.showOpenDialog(null);

			if (newFile != null)
				canvas.fromTextFile (newFile);
		});

		class saveBinaryHandler implements EventHandler<ActionEvent>
		{
			@Override
			public void handle (ActionEvent e)
			{
				fileChooser.setTitle("Save drawing as");
				File newFile = fileChooser.showSaveDialog(null);

				if (newFile != null)
					canvas.toBinaryFile (newFile);
			}
		}
		miSaveB.setOnAction(new saveBinaryHandler());

		miLoadB.setOnAction(e -> {
			fileChooser.setTitle("Load drawing");
			File newFile = fileChooser.showOpenDialog(null);

			if (newFile != null)
				canvas.fromBinaryFile (newFile);
		});

		mainPane.setBottom(menuBar);
	}

	/**
	 * Launches the JavaFX application.
	 *
	 * @param args command-line arguments
	 */
    public static void main (String[] args)
	{
		launch(args);
	}

	/**
	 * Applies hover effects to toolbar buttons to improve UI feedback.
	 *
	 * @param b the button to apply hover styling to
	 */
	private void wireToolButtonHover (Button b)
	{
		b.setCursor (Cursor.HAND);
		b.setOnMouseEntered (e -> b.setStyle (TOOL_BUTTON_STYLE_HOVER));
		b.setOnMouseExited (e -> b.setStyle (TOOL_BUTTON_STYLE));
	} // – generated by genAI

	/**
	 * Creates a vertical separator used to visually group toolbar elements.
	 *
	 * @return a styled vertical separator
	 */
	private Separator toolbarRule ()
	{
		Separator s = new Separator ();
		s.setOrientation (Orientation.VERTICAL);
		s.setPadding (new Insets (0, 6, 0, 6));
		s.setMaxHeight (22);
		s.setStyle ("-fx-opacity: 0.55;");
		return s;
	} // – generated by genAI
}
